GET http://localhost:3000/users HTTP/1.1
###

GET http://localhost:3000/users/5beca464-03c0-4d8b-bbde-b5f38492612c HTTP/1.1

###

POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "name": "Altamiro Ribeiro da Rocha Júnior",
    "email": "juniorrocha@gmail.com"
}

###

POST http://localhost:3000/todos HTTP/1.1
content-type: application/json
x-user-id: 5beca464-03c0-4d8b-bbde-b5f38492612c

{
    "title": "task 2323232"
}

# ###
# POST http://localhost:3000/checkout HTTP/1.1
# content-type: application/json
# x-user-id: 5beca464-03c0-4d8b-bbde-b5f38492612c


###
POST http://localhost:3000/checkout HTTP/1.1
# content-type: application/json
x-user-id: 0f9bd2ee-147d-40e7-b427-7ba8dc196418
